ALTER TABLE "posts"
ADD COLUMN IF NOT EXISTS "company_name" VARCHAR(255),
ADD COLUMN IF NOT EXISTS "application_deadline" TIMESTAMP(6),
ADD COLUMN IF NOT EXISTS "stipend" VARCHAR(100),
ADD COLUMN IF NOT EXISTS "duration" VARCHAR(100);
